package com.github.jingerjesus.pandoracompiler;

public enum TokenName {
        UINT, INT, UDOUBLE, DOUBLE, BOOL, CHAR, OPERATION, END, FLAG, SUBROUTINE, RETURN, STOP, MODE, UNKNOWN,
        OPENBRACKET, CLOSEBRACKET, JUMP, CONDJUMP, HALT, DECVALUE, HEXVALUE, BINVALUE, NAME, CONDITION
}
