public enum TokenName {
        UINT, INT, UDOUBLE, DOUBLE, BOOL, CHAR, OPERATION, END, FLAG, SUBROUTINE, RETURN, STOP, MODE, UNKNOWN,
        OPENBRACKET, CLOSEBRACKET, JUMP, CONDJUMP, HALT, VALUE, NAME, CONDITION
}
